-- Table: public.department

-- DROP TABLE public.department;

CREATE TABLE public.department
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description character varying(2500) COLLATE pg_catalog."default",
    CONSTRAINT department_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.department
    OWNER to postgres;
	
	
	
	
-- Table: public.employee

-- DROP TABLE public.employee;

CREATE TABLE public.employee
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default",
    address character varying(100) COLLATE pg_catalog."default",
    designation character varying(100) COLLATE pg_catalog."default",
    salary double precision,
    department_id bigint NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (id),
    CONSTRAINT department_id FOREIGN KEY (department_id)
        REFERENCES public.department (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.employee
    OWNER to postgres;
-- Index: fki_department_Id

-- DROP INDEX public."fki_department_Id";

CREATE INDEX "fki_department_Id"
    ON public.employee USING btree
    (department_id ASC NULLS LAST)
    TABLESPACE pg_default;